-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fips_implementations]
import Aeneas
open Aeneas.Std
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace fips_implementations

/- [fips_implementations::algorithms::sha1::u32x4]
   Source: 'src/algorithms/sha1.rs', lines 9:0-9:53 -/
def algorithms.sha1.u32x4 := U32 × U32 × U32 × U32

/- [fips_implementations::algorithms::sha1::{core::clone::Clone for fips_implementations::algorithms::sha1::u32x4}#9::clone]:
   Source: 'src/algorithms/sha1.rs', lines 7:9-7:14 -/
def algorithms.sha1.Clonefips_implementationsalgorithmssha1u32x4.clone
  (self : algorithms.sha1.u32x4) : Result algorithms.sha1.u32x4 :=
  Result.ok self

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::clone::Clone for fips_implementations::algorithms::sha1::u32x4}#9]
   Source: 'src/algorithms/sha1.rs', lines 7:9-7:14 -/
@[reducible]
def core.clone.Clonefips_implementationsalgorithmssha1u32x4 : core.clone.Clone
  algorithms.sha1.u32x4 := {
  clone := algorithms.sha1.Clonefips_implementationsalgorithmssha1u32x4.clone
}

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::marker::Copy for fips_implementations::algorithms::sha1::u32x4}#10]
   Source: 'src/algorithms/sha1.rs', lines 7:16-7:20 -/
@[reducible]
def core.marker.Copyfips_implementationsalgorithmssha1u32x4 : core.marker.Copy
  algorithms.sha1.u32x4 := {
  cloneInst := core.clone.Clonefips_implementationsalgorithmssha1u32x4
}

/- Trait declaration: [core::ops::arith::Add]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:25
   Name pattern: core::ops::arith::Add -/
structure core.ops.arith.Add (Self : Type) (Rhs : Type) where
  Output : Type
  add : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::arith::Add<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}::add]:
   Source: 'src/algorithms/sha1.rs', lines 14:4-21:5 -/
def
  algorithms.sha1.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.add
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  let i8 := core.num.U32.wrapping_add i i4
  let i9 := core.num.U32.wrapping_add i1 i5
  let i10 := core.num.U32.wrapping_add i2 i6
  let i11 := core.num.U32.wrapping_add i3 i7
  Result.ok (i8, i9, i10, i11)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::arith::Add<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}]
   Source: 'src/algorithms/sha1.rs', lines 11:0-22:1 -/
@[reducible]
def
  core.ops.arith.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.arith.Add algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  add :=
    algorithms.sha1.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.add
}

/- Trait declaration: [core::ops::arith::Sub]
   Source: '/rustc/library/core/src/ops/arith.rs', lines 185:0-185:25
   Name pattern: core::ops::arith::Sub -/
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) where
  Output : Type
  sub : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::arith::Sub<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#1::sub]:
   Source: 'src/algorithms/sha1.rs', lines 27:4-34:5 -/
def
  algorithms.sha1.Subfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.sub
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  let i8 := core.num.U32.wrapping_sub i i4
  let i9 := core.num.U32.wrapping_sub i1 i5
  let i10 := core.num.U32.wrapping_sub i2 i6
  let i11 := core.num.U32.wrapping_sub i3 i7
  Result.ok (i8, i9, i10, i11)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::arith::Sub<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#1]
   Source: 'src/algorithms/sha1.rs', lines 24:0-35:1 -/
@[reducible]
def
  core.ops.arith.Subfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.arith.Sub algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  sub :=
    algorithms.sha1.Subfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.sub
}

/- Trait declaration: [core::ops::bit::BitAnd]
   Source: '/rustc/library/core/src/ops/bit.rs', lines 144:0-144:28
   Name pattern: core::ops::bit::BitAnd -/
structure core.ops.bit.BitAnd (Self : Type) (Rhs : Type) where
  Output : Type
  bitand : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::bit::BitAnd<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#2::bitand]:
   Source: 'src/algorithms/sha1.rs', lines 40:4-47:5 -/
def
  algorithms.sha1.BitAndfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitand
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  Result.ok (i &&& i4, i1 &&& i5, i2 &&& i6, i3 &&& i7)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::BitAnd<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#2]
   Source: 'src/algorithms/sha1.rs', lines 37:0-48:1 -/
@[reducible]
def
  core.ops.bit.BitAndfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.bit.BitAnd algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  bitand :=
    algorithms.sha1.BitAndfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitand
}

/- Trait declaration: [core::ops::bit::BitOr]
   Source: '/rustc/library/core/src/ops/bit.rs', lines 244:0-244:27
   Name pattern: core::ops::bit::BitOr -/
structure core.ops.bit.BitOr (Self : Type) (Rhs : Type) where
  Output : Type
  bitor : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::bit::BitOr<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#3::bitor]:
   Source: 'src/algorithms/sha1.rs', lines 53:4-60:5 -/
def
  algorithms.sha1.BitOrfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitor
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  Result.ok (i ||| i4, i1 ||| i5, i2 ||| i6, i3 ||| i7)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::BitOr<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#3]
   Source: 'src/algorithms/sha1.rs', lines 50:0-61:1 -/
@[reducible]
def
  core.ops.bit.BitOrfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.bit.BitOr algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  bitor :=
    algorithms.sha1.BitOrfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitor
}

/- Trait declaration: [core::ops::bit::BitXor]
   Source: '/rustc/library/core/src/ops/bit.rs', lines 344:0-344:28
   Name pattern: core::ops::bit::BitXor -/
structure core.ops.bit.BitXor (Self : Type) (Rhs : Type) where
  Output : Type
  bitxor : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::bit::BitXor<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#4::bitxor]:
   Source: 'src/algorithms/sha1.rs', lines 66:4-73:5 -/
def
  algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  Result.ok (i ^^^ i4, i1 ^^^ i5, i2 ^^^ i6, i3 ^^^ i7)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::BitXor<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#4]
   Source: 'src/algorithms/sha1.rs', lines 63:0-74:1 -/
@[reducible]
def
  core.ops.bit.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.bit.BitXor algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  bitxor :=
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
}

/- Trait declaration: [core::ops::bit::Shl]
   Source: '/rustc/library/core/src/ops/bit.rs', lines 443:0-443:25
   Name pattern: core::ops::bit::Shl -/
structure core.ops.bit.Shl (Self : Type) (Rhs : Type) where
  Output : Type
  shl : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::bit::Shl<usize> for fips_implementations::algorithms::sha1::u32x4}#5::shl]:
   Source: 'src/algorithms/sha1.rs', lines 79:4-81:5 -/
def algorithms.sha1.Shlfips_implementationsalgorithmssha1u32x4Usize.shl
  (self : algorithms.sha1.u32x4) (amt : Usize) :
  Result algorithms.sha1.u32x4
  :=
  do
  let (i, i1, i2, i3) := self
  let i4 ← i <<< amt
  let i5 ← i1 <<< amt
  let i6 ← i2 <<< amt
  let i7 ← i3 <<< amt
  Result.ok (i4, i5, i6, i7)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::Shl<usize> for fips_implementations::algorithms::sha1::u32x4}#5]
   Source: 'src/algorithms/sha1.rs', lines 76:0-82:1 -/
@[reducible]
def core.ops.bit.Shlfips_implementationsalgorithmssha1u32x4Usize :
  core.ops.bit.Shl algorithms.sha1.u32x4 Usize := {
  Output := algorithms.sha1.u32x4
  shl := algorithms.sha1.Shlfips_implementationsalgorithmssha1u32x4Usize.shl
}

/- [fips_implementations::algorithms::sha1::{core::ops::bit::Shl<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#6::shl]:
   Source: 'src/algorithms/sha1.rs', lines 87:4-94:5 -/
def
  algorithms.sha1.Shlfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.shl
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  do
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  let i8 ← i <<< i4
  let i9 ← i1 <<< i5
  let i10 ← i2 <<< i6
  let i11 ← i3 <<< i7
  Result.ok (i8, i9, i10, i11)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::Shl<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#6]
   Source: 'src/algorithms/sha1.rs', lines 84:0-95:1 -/
@[reducible]
def
  core.ops.bit.Shlfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.bit.Shl algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  shl :=
    algorithms.sha1.Shlfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.shl
}

/- Trait declaration: [core::ops::bit::Shr]
   Source: '/rustc/library/core/src/ops/bit.rs', lines 561:0-561:25
   Name pattern: core::ops::bit::Shr -/
structure core.ops.bit.Shr (Self : Type) (Rhs : Type) where
  Output : Type
  shr : Self → Rhs → Result Output

/- [fips_implementations::algorithms::sha1::{core::ops::bit::Shr<usize> for fips_implementations::algorithms::sha1::u32x4}#7::shr]:
   Source: 'src/algorithms/sha1.rs', lines 100:4-102:5 -/
def algorithms.sha1.Shrfips_implementationsalgorithmssha1u32x4Usize.shr
  (self : algorithms.sha1.u32x4) (amt : Usize) :
  Result algorithms.sha1.u32x4
  :=
  do
  let (i, i1, i2, i3) := self
  let i4 ← i >>> amt
  let i5 ← i1 >>> amt
  let i6 ← i2 >>> amt
  let i7 ← i3 >>> amt
  Result.ok (i4, i5, i6, i7)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::Shr<usize> for fips_implementations::algorithms::sha1::u32x4}#7]
   Source: 'src/algorithms/sha1.rs', lines 97:0-103:1 -/
@[reducible]
def core.ops.bit.Shrfips_implementationsalgorithmssha1u32x4Usize :
  core.ops.bit.Shr algorithms.sha1.u32x4 Usize := {
  Output := algorithms.sha1.u32x4
  shr := algorithms.sha1.Shrfips_implementationsalgorithmssha1u32x4Usize.shr
}

/- [fips_implementations::algorithms::sha1::{core::ops::bit::Shr<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#8::shr]:
   Source: 'src/algorithms/sha1.rs', lines 108:4-115:5 -/
def
  algorithms.sha1.Shrfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.shr
  (self : algorithms.sha1.u32x4) (rhs : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  do
  let (i, i1, i2, i3) := self
  let (i4, i5, i6, i7) := rhs
  let i8 ← i >>> i4
  let i9 ← i1 >>> i5
  let i10 ← i2 >>> i6
  let i11 ← i3 >>> i7
  Result.ok (i8, i9, i10, i11)

/- Trait implementation: [fips_implementations::algorithms::sha1::{core::ops::bit::Shr<fips_implementations::algorithms::sha1::u32x4> for fips_implementations::algorithms::sha1::u32x4}#8]
   Source: 'src/algorithms/sha1.rs', lines 105:0-116:1 -/
@[reducible]
def
  core.ops.bit.Shrfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4
  : core.ops.bit.Shr algorithms.sha1.u32x4 algorithms.sha1.u32x4 := {
  Output := algorithms.sha1.u32x4
  shr :=
    algorithms.sha1.Shrfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.shr
}

/- [fips_implementations::algorithms::sha1::INITIAL_STATE]
   Source: 'src/algorithms/sha1.rs', lines 119:0-119:93 -/
def algorithms.sha1.INITIAL_STATE_body : Result (Array U32 5#usize) :=
  Result.ok
  (Array.make 5#usize [
    1732584193#u32, 4023233417#u32, 2562383102#u32, 271733878#u32,
    3285377520#u32
    ])
def algorithms.sha1.INITIAL_STATE : Array U32 5#usize :=
  eval_global algorithms.sha1.INITIAL_STATE_body

/- [fips_implementations::algorithms::sha1::CHUNK_SIZE]
   Source: 'src/algorithms/sha1.rs', lines 122:0-122:29 -/
def algorithms.sha1.CHUNK_SIZE_body : Result Usize := Result.ok 64#usize
def algorithms.sha1.CHUNK_SIZE : Usize :=
  eval_global algorithms.sha1.CHUNK_SIZE_body

/- [fips_implementations::algorithms::sha1::K0]
   Source: 'src/algorithms/sha1.rs', lines 125:0-125:30 -/
def algorithms.sha1.K0_body : Result U32 := Result.ok 1518500249#u32
def algorithms.sha1.K0 : U32 := eval_global algorithms.sha1.K0_body

/- [fips_implementations::algorithms::sha1::K1]
   Source: 'src/algorithms/sha1.rs', lines 126:0-126:30 -/
def algorithms.sha1.K1_body : Result U32 := Result.ok 1859775393#u32
def algorithms.sha1.K1 : U32 := eval_global algorithms.sha1.K1_body

/- [fips_implementations::algorithms::sha1::K2]
   Source: 'src/algorithms/sha1.rs', lines 127:0-127:30 -/
def algorithms.sha1.K2_body : Result U32 := Result.ok 2400959708#u32
def algorithms.sha1.K2 : U32 := eval_global algorithms.sha1.K2_body

/- [fips_implementations::algorithms::sha1::K3]
   Source: 'src/algorithms/sha1.rs', lines 128:0-128:30 -/
def algorithms.sha1.K3_body : Result U32 := Result.ok 3395469782#u32
def algorithms.sha1.K3 : U32 := eval_global algorithms.sha1.K3_body

/- [fips_implementations::algorithms::sha1::sha1_first]:
   Source: 'src/algorithms/sha1.rs', lines 132:0-134:1 -/
def algorithms.sha1.sha1_first (w0 : algorithms.sha1.u32x4) : Result U32 :=
  let (i, _, _, _) := w0
  Result.ok i

/- [fips_implementations::algorithms::sha1::sha1_first_add]:
   Source: 'src/algorithms/sha1.rs', lines 138:0-141:1 -/
def algorithms.sha1.sha1_first_add
  (e : U32) (w0 : algorithms.sha1.u32x4) : Result algorithms.sha1.u32x4 :=
  let (a, b, c, d) := w0
  let i := core.num.U32.wrapping_add e a
  Result.ok (i, b, c, d)

/- [fips_implementations::algorithms::sha1::sha1msg1]:
   Source: 'src/algorithms/sha1.rs', lines 144:0-148:1 -/
def algorithms.sha1.sha1msg1
  (a : algorithms.sha1.u32x4) (b : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (_, _, w2, w3) := a
  let (w4, w5, _, _) := b
  algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
    a (w2, w3, w4, w5)

/- [fips_implementations::algorithms::sha1::sha1msg2]:
   Source: 'src/algorithms/sha1.rs', lines 151:0-161:1 -/
def algorithms.sha1.sha1msg2
  (a : algorithms.sha1.u32x4) (b : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (x0, x1, x2, x3) := a
  let (_, w13, w14, w15) := b
  let w16 := core.num.U32.rotate_left (x0 ^^^ w13) 1#u32
  let w17 := core.num.U32.rotate_left (x1 ^^^ w14) 1#u32
  let w18 := core.num.U32.rotate_left (x2 ^^^ w15) 1#u32
  let w19 := core.num.U32.rotate_left (x3 ^^^ w16) 1#u32
  Result.ok (w16, w17, w18, w19)

/- [fips_implementations::algorithms::sha1::sha1_first_half]:
   Source: 'src/algorithms/sha1.rs', lines 165:0-167:1 -/
def algorithms.sha1.sha1_first_half
  (abcd : algorithms.sha1.u32x4) (msg : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  do
  let i ← algorithms.sha1.sha1_first abcd
  let i1 := core.num.U32.rotate_left i 30#u32
  algorithms.sha1.sha1_first_add i1 msg

/- [fips_implementations::algorithms::sha1::sha1_digest_round_x4::K1V]
   Source: 'src/algorithms/sha1.rs', lines 173:4-173:45 -/
def algorithms.sha1.sha1_digest_round_x4.K1V_body
  : Result algorithms.sha1.u32x4 :=
  Result.ok
  (algorithms.sha1.K1,
  algorithms.sha1.K1,
  algorithms.sha1.K1,
  algorithms.sha1.K1)
def algorithms.sha1.sha1_digest_round_x4.K1V : algorithms.sha1.u32x4 :=
  eval_global algorithms.sha1.sha1_digest_round_x4.K1V_body

/- [fips_implementations::algorithms::sha1::sha1rnds4p]:
   Source: 'src/algorithms/sha1.rs', lines 226:0-262:1 -/
def algorithms.sha1.sha1rnds4p
  (abcd : algorithms.sha1.u32x4) (msg : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (a, b, c, d) := abcd
  let (t, u, v, w) := msg
  let i := core.num.U32.rotate_left a 5#u32
  let i1 := core.num.U32.wrapping_add 0#u32 i
  let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
  let e := core.num.U32.wrapping_add i2 t
  let b1 := core.num.U32.rotate_left b 30#u32
  let i3 := core.num.U32.rotate_left e 5#u32
  let i4 := core.num.U32.wrapping_add d i3
  let i5 := core.num.U32.wrapping_add i4 ((a ^^^ b1) ^^^ c)
  let d1 := core.num.U32.wrapping_add i5 u
  let a1 := core.num.U32.rotate_left a 30#u32
  let i6 := core.num.U32.rotate_left d1 5#u32
  let i7 := core.num.U32.wrapping_add c i6
  let i8 := core.num.U32.wrapping_add i7 ((e ^^^ a1) ^^^ b1)
  let c1 := core.num.U32.wrapping_add i8 v
  let e1 := core.num.U32.rotate_left e 30#u32
  let i9 := core.num.U32.rotate_left c1 5#u32
  let i10 := core.num.U32.wrapping_add b1 i9
  let i11 := core.num.U32.wrapping_add i10 ((d1 ^^^ e1) ^^^ a1)
  let b2 := core.num.U32.wrapping_add i11 w
  let d2 := core.num.U32.rotate_left d1 30#u32
  Result.ok (b2, c1, d2, e1)

/- [fips_implementations::algorithms::sha1::sha1_digest_round_x4::K2V]
   Source: 'src/algorithms/sha1.rs', lines 174:4-174:45 -/
def algorithms.sha1.sha1_digest_round_x4.K2V_body
  : Result algorithms.sha1.u32x4 :=
  Result.ok
  (algorithms.sha1.K2,
  algorithms.sha1.K2,
  algorithms.sha1.K2,
  algorithms.sha1.K2)
def algorithms.sha1.sha1_digest_round_x4.K2V : algorithms.sha1.u32x4 :=
  eval_global algorithms.sha1.sha1_digest_round_x4.K2V_body

/- [fips_implementations::algorithms::sha1::sha1rnds4m]:
   Source: 'src/algorithms/sha1.rs', lines 265:0-301:1 -/
def algorithms.sha1.sha1rnds4m
  (abcd : algorithms.sha1.u32x4) (msg : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (a, b, c, d) := abcd
  let (t, u, v, w) := msg
  let i := core.num.U32.rotate_left a 5#u32
  let i1 := core.num.U32.wrapping_add 0#u32 i
  let i2 :=
    core.num.U32.wrapping_add i1 (((b &&& c) ^^^ (b &&& d)) ^^^ (c &&& d))
  let e := core.num.U32.wrapping_add i2 t
  let b1 := core.num.U32.rotate_left b 30#u32
  let i3 := core.num.U32.rotate_left e 5#u32
  let i4 := core.num.U32.wrapping_add d i3
  let i5 :=
    core.num.U32.wrapping_add i4 (((a &&& b1) ^^^ (a &&& c)) ^^^ (b1 &&& c))
  let d1 := core.num.U32.wrapping_add i5 u
  let a1 := core.num.U32.rotate_left a 30#u32
  let i6 := core.num.U32.rotate_left d1 5#u32
  let i7 := core.num.U32.wrapping_add c i6
  let i8 :=
    core.num.U32.wrapping_add i7 (((e &&& a1) ^^^ (e &&& b1)) ^^^ (a1 &&& b1))
  let c1 := core.num.U32.wrapping_add i8 v
  let e1 := core.num.U32.rotate_left e 30#u32
  let i9 := core.num.U32.rotate_left c1 5#u32
  let i10 := core.num.U32.wrapping_add b1 i9
  let i11 :=
    core.num.U32.wrapping_add i10 (((d1 &&& e1) ^^^ (d1 &&& a1)) ^^^ (e1 &&&
      a1))
  let b2 := core.num.U32.wrapping_add i11 w
  let d2 := core.num.U32.rotate_left d1 30#u32
  Result.ok (b2, c1, d2, e1)

/- [fips_implementations::algorithms::sha1::sha1_digest_round_x4::K3V]
   Source: 'src/algorithms/sha1.rs', lines 175:4-175:45 -/
def algorithms.sha1.sha1_digest_round_x4.K3V_body
  : Result algorithms.sha1.u32x4 :=
  Result.ok
  (algorithms.sha1.K3,
  algorithms.sha1.K3,
  algorithms.sha1.K3,
  algorithms.sha1.K3)
def algorithms.sha1.sha1_digest_round_x4.K3V : algorithms.sha1.u32x4 :=
  eval_global algorithms.sha1.sha1_digest_round_x4.K3V_body

/- [fips_implementations::algorithms::sha1::sha1_digest_round_x4::K0V]
   Source: 'src/algorithms/sha1.rs', lines 172:4-172:45 -/
def algorithms.sha1.sha1_digest_round_x4.K0V_body
  : Result algorithms.sha1.u32x4 :=
  Result.ok
  (algorithms.sha1.K0,
  algorithms.sha1.K0,
  algorithms.sha1.K0,
  algorithms.sha1.K0)
def algorithms.sha1.sha1_digest_round_x4.K0V : algorithms.sha1.u32x4 :=
  eval_global algorithms.sha1.sha1_digest_round_x4.K0V_body

/- [fips_implementations::algorithms::sha1::sha1rnds4c]:
   Source: 'src/algorithms/sha1.rs', lines 187:0-223:1 -/
def algorithms.sha1.sha1rnds4c
  (abcd : algorithms.sha1.u32x4) (msg : algorithms.sha1.u32x4) :
  Result algorithms.sha1.u32x4
  :=
  let (a, b, c, d) := abcd
  let (t, u, v, w) := msg
  let i := core.num.U32.rotate_left a 5#u32
  let i1 := core.num.U32.wrapping_add 0#u32 i
  let i2 := core.num.U32.wrapping_add i1 (d ^^^ (b &&& (c ^^^ d)))
  let e := core.num.U32.wrapping_add i2 t
  let b1 := core.num.U32.rotate_left b 30#u32
  let i3 := core.num.U32.rotate_left e 5#u32
  let i4 := core.num.U32.wrapping_add d i3
  let i5 := core.num.U32.wrapping_add i4 (c ^^^ (a &&& (b1 ^^^ c)))
  let d1 := core.num.U32.wrapping_add i5 u
  let a1 := core.num.U32.rotate_left a 30#u32
  let i6 := core.num.U32.rotate_left d1 5#u32
  let i7 := core.num.U32.wrapping_add c i6
  let i8 := core.num.U32.wrapping_add i7 (b1 ^^^ (e &&& (a1 ^^^ b1)))
  let c1 := core.num.U32.wrapping_add i8 v
  let e1 := core.num.U32.rotate_left e 30#u32
  let i9 := core.num.U32.rotate_left c1 5#u32
  let i10 := core.num.U32.wrapping_add b1 i9
  let i11 := core.num.U32.wrapping_add i10 (a1 ^^^ (d1 &&& (e1 ^^^ a1)))
  let b2 := core.num.U32.wrapping_add i11 w
  let d2 := core.num.U32.rotate_left d1 30#u32
  Result.ok (b2, c1, d2, e1)

/- [fips_implementations::algorithms::sha1::sha1_digest_round_x4]:
   Source: 'src/algorithms/sha1.rs', lines 171:0-184:1 -/
def algorithms.sha1.sha1_digest_round_x4
  (abcd : algorithms.sha1.u32x4) (work : algorithms.sha1.u32x4) (i : I8) :
  Result algorithms.sha1.u32x4
  :=
  match i with
  | 0#scalar =>
    do
    let ux ←
      algorithms.sha1.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.add
        work algorithms.sha1.sha1_digest_round_x4.K0V
    algorithms.sha1.sha1rnds4c abcd ux
  | 1#scalar =>
    do
    let ux ←
      algorithms.sha1.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.add
        work algorithms.sha1.sha1_digest_round_x4.K1V
    algorithms.sha1.sha1rnds4p abcd ux
  | 2#scalar =>
    do
    let ux ←
      algorithms.sha1.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.add
        work algorithms.sha1.sha1_digest_round_x4.K2V
    algorithms.sha1.sha1rnds4m abcd ux
  | 3#scalar =>
    do
    let ux ←
      algorithms.sha1.Addfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.add
        work algorithms.sha1.sha1_digest_round_x4.K3V
    algorithms.sha1.sha1rnds4p abcd ux
  | _ => Result.ok (0#u32, 0#u32, 0#u32, 0#u32)

/- [fips_implementations::algorithms::sha1::process_loop]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 307:4-314:5 -/
divergent def algorithms.sha1.process_loop_loop
  (block : Array U8 64#usize) (words : Array U32 16#usize) (index : Usize) :
  Result (Array U32 16#usize)
  :=
  if index < 16#usize
  then
    do
    let off ← index * 4#usize
    let i ← off + 3#usize
    let i1 ← Array.index_usize block i
    let i2 ← Scalar.cast .U32 i1
    let i3 ← off + 2#usize
    let i4 ← Array.index_usize block i3
    let i5 ← Scalar.cast .U32 i4
    let i6 ← i5 <<< 8#i32
    let i7 ← off + 1#usize
    let i8 ← Array.index_usize block i7
    let i9 ← Scalar.cast .U32 i8
    let i10 ← i9 <<< 16#i32
    let i11 ← Array.index_usize block off
    let i12 ← Scalar.cast .U32 i11
    let i13 ← i12 <<< 24#i32
    let (_, index_mut_back) ← Array.index_mut_usize words index
    let index1 ← index + 1#usize
    let words1 := index_mut_back (((i2 ||| i6) ||| i10) ||| i13)
    algorithms.sha1.process_loop_loop block words1 index1
  else Result.ok words

/- [fips_implementations::algorithms::sha1::process_loop]:
   Source: 'src/algorithms/sha1.rs', lines 304:0-316:1 -/
def algorithms.sha1.process_loop
  (block : Array U8 64#usize) : Result (Array U32 16#usize) :=
  let words := Array.repeat 16#usize 0#u32
  algorithms.sha1.process_loop_loop block words 0#usize

/- [fips_implementations::algorithms::sha1::process_rounds_0]:
   Source: 'src/algorithms/sha1.rs', lines 331:0-347:1 -/
def algorithms.sha1.process_rounds_0
  (h0 : algorithms.sha1.u32x4) (state : Array U32 5#usize)
  (words : Array U32 16#usize) :
  Result (algorithms.sha1.u32x4 × algorithms.sha1.u32x4 ×
    algorithms.sha1.u32x4 × algorithms.sha1.u32x4 × algorithms.sha1.u32x4 ×
    algorithms.sha1.u32x4)
  :=
  do
  let i ← Array.index_usize words 0#usize
  let i1 ← Array.index_usize words 1#usize
  let i2 ← Array.index_usize words 2#usize
  let i3 ← Array.index_usize words 3#usize
  let i4 ← Array.index_usize state 4#usize
  let ux ← algorithms.sha1.sha1_first_add i4 (i, i1, i2, i3)
  let h1 ← algorithms.sha1.sha1_digest_round_x4 h0 ux 0#i8
  let i5 ← Array.index_usize words 4#usize
  let i6 ← Array.index_usize words 5#usize
  let i7 ← Array.index_usize words 6#usize
  let i8 ← Array.index_usize words 7#usize
  let ux1 ← algorithms.sha1.sha1_first_half h0 (i5, i6, i7, i8)
  let h01 ← algorithms.sha1.sha1_digest_round_x4 h1 ux1 0#i8
  let i9 ← Array.index_usize words 8#usize
  let i10 ← Array.index_usize words 9#usize
  let i11 ← Array.index_usize words 10#usize
  let i12 ← Array.index_usize words 11#usize
  let ux2 ← algorithms.sha1.sha1_first_half h1 (i9, i10, i11, i12)
  let h11 ← algorithms.sha1.sha1_digest_round_x4 h01 ux2 0#i8
  let i13 ← Array.index_usize words 12#usize
  let i14 ← Array.index_usize words 13#usize
  let i15 ← Array.index_usize words 14#usize
  let i16 ← Array.index_usize words 15#usize
  let ux3 ← algorithms.sha1.sha1_first_half h01 (i13, i14, i15, i16)
  let h02 ← algorithms.sha1.sha1_digest_round_x4 h11 ux3 0#i8
  let ux4 ← algorithms.sha1.sha1msg1 (i, i1, i2, i3) (i5, i6, i7, i8)
  let ux5 ←
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
      ux4 (i9, i10, i11, i12)
  let w4 ← algorithms.sha1.sha1msg2 ux5 (i13, i14, i15, i16)
  let ux6 ← algorithms.sha1.sha1_first_half h11 w4
  let h12 ← algorithms.sha1.sha1_digest_round_x4 h02 ux6 0#i8
  Result.ok (h02, h12, (i5, i6, i7, i8), (i9, i10, i11, i12), (i13, i14, i15,
    i16), w4)

/- [fips_implementations::algorithms::sha1::process_rounds_i]:
   Source: 'src/algorithms/sha1.rs', lines 349:0-369:1 -/
def algorithms.sha1.process_rounds_i
  (h0 : algorithms.sha1.u32x4) (h1 : algorithms.sha1.u32x4)
  (w1 : algorithms.sha1.u32x4) (w2 : algorithms.sha1.u32x4)
  (w3 : algorithms.sha1.u32x4) (w4 : algorithms.sha1.u32x4) (i : I8) :
  Result (algorithms.sha1.u32x4 × algorithms.sha1.u32x4 ×
    algorithms.sha1.u32x4 × algorithms.sha1.u32x4 × algorithms.sha1.u32x4 ×
    algorithms.sha1.u32x4)
  :=
  do
  let ux ← algorithms.sha1.sha1msg1 w1 w2
  let ux1 ←
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
      ux w3
  let w0 ← algorithms.sha1.sha1msg2 ux1 w4
  let ux2 ← algorithms.sha1.sha1_first_half h0 w0
  let h01 ← algorithms.sha1.sha1_digest_round_x4 h1 ux2 i
  let ux3 ← algorithms.sha1.sha1msg1 w2 w3
  let ux4 ←
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
      ux3 w4
  let w11 ← algorithms.sha1.sha1msg2 ux4 w0
  let ux5 ← algorithms.sha1.sha1_first_half h1 w11
  let h11 ← algorithms.sha1.sha1_digest_round_x4 h01 ux5 i
  let ux6 ← algorithms.sha1.sha1msg1 w3 w4
  let ux7 ←
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
      ux6 w0
  let w21 ← algorithms.sha1.sha1msg2 ux7 w11
  let ux8 ← algorithms.sha1.sha1_first_half h01 w21
  let h02 ← algorithms.sha1.sha1_digest_round_x4 h11 ux8 i
  let ux9 ← algorithms.sha1.sha1msg1 w4 w0
  let ux10 ←
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
      ux9 w11
  let w31 ← algorithms.sha1.sha1msg2 ux10 w21
  let ux11 ← algorithms.sha1.sha1_first_half h11 w31
  let h12 ← algorithms.sha1.sha1_digest_round_x4 h02 ux11 i
  let ux12 ← algorithms.sha1.sha1msg1 w0 w11
  let ux13 ←
    algorithms.sha1.BitXorfips_implementationsalgorithmssha1u32x4fips_implementationsalgorithmssha1u32x4.bitxor
      ux12 w21
  let w41 ← algorithms.sha1.sha1msg2 ux13 w31
  let ux14 ← algorithms.sha1.sha1_first_half h02 w41
  let h03 ← algorithms.sha1.sha1_digest_round_x4 h12 ux14 i
  Result.ok (h03, h12, w11, w21, w31, w41)

/- [fips_implementations::algorithms::sha1::process]:
   Source: 'src/algorithms/sha1.rs', lines 371:0-388:1 -/
def algorithms.sha1.process
  (state : Array U32 5#usize) (block : Array U8 64#usize) :
  Result (Array U32 5#usize)
  :=
  do
  let words ← algorithms.sha1.process_loop block
  let i ← Array.index_usize state 0#usize
  let i1 ← Array.index_usize state 1#usize
  let i2 ← Array.index_usize state 2#usize
  let i3 ← Array.index_usize state 3#usize
  let t ← algorithms.sha1.process_rounds_0 (i, i1, i2, i3) state words
  let (h0, h1, w1, w2, w3, w4) := t
  let t1 ← algorithms.sha1.process_rounds_i h0 h1 w1 w2 w3 w4 1#i8
  let (h01, h11, w11, w21, w31, w41) := t1
  let t2 ← algorithms.sha1.process_rounds_i h01 h11 w11 w21 w31 w41 2#i8
  let (h02, h12, w12, w22, w32, w42) := t2
  let t3 ← algorithms.sha1.process_rounds_i h02 h12 w12 w22 w32 w42 3#i8
  let (h03, h13, _, _, _, _) := t3
  let i4 ← algorithms.sha1.sha1_first h13
  let e := core.num.U32.rotate_left i4 30#u32
  let (a, b, c, d) := h03
  let i5 ← Array.index_usize state 0#usize
  let i6 := core.num.U32.wrapping_add i5 a
  let state1 ← Array.update_usize state 0#usize i6
  let i7 ← Array.index_usize state1 1#usize
  let i8 := core.num.U32.wrapping_add i7 b
  let state2 ← Array.update_usize state1 1#usize i8
  let i9 ← Array.index_usize state2 2#usize
  let i10 := core.num.U32.wrapping_add i9 c
  let state3 ← Array.update_usize state2 2#usize i10
  let i11 ← Array.index_usize state3 3#usize
  let i12 := core.num.U32.wrapping_add i11 d
  let state4 ← Array.update_usize state3 3#usize i12
  let i13 ← Array.index_usize state4 4#usize
  let i14 := core.num.U32.wrapping_add i13 e
  let (_, index_mut_back) ← Array.index_mut_usize state4 4#usize
  Result.ok (index_mut_back i14)

/- [fips_implementations::algorithms::sha1::process_loop_aux]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 393:4-400:5 -/
divergent def algorithms.sha1.process_loop_aux_loop
  (block : Array U8 64#usize) (w : alloc.vec.Vec U32) (i : Usize) :
  Result (alloc.vec.Vec U32)
  :=
  if i < 16#usize
  then
    do
    let off ← i * 4#usize
    let i1 ← Array.index_usize block off
    let i2 ← Scalar.cast .U32 i1
    let i3 ← i2 <<< 24#i32
    let i4 ← off + 1#usize
    let i5 ← Array.index_usize block i4
    let i6 ← Scalar.cast .U32 i5
    let i7 ← i6 <<< 16#i32
    let i8 ← off + 2#usize
    let i9 ← Array.index_usize block i8
    let i10 ← Scalar.cast .U32 i9
    let i11 ← i10 <<< 8#i32
    let i12 ← off + 3#usize
    let i13 ← Array.index_usize block i12
    let i14 ← Scalar.cast .U32 i13
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSliceTInst U32)
        w i
    let i15 ← i + 1#usize
    let w1 := index_mut_back (((i3 ||| i7) ||| i11) ||| i14)
    algorithms.sha1.process_loop_aux_loop block w1 i15
  else Result.ok w

/- [fips_implementations::algorithms::sha1::process_loop_aux]:
   Source: 'src/algorithms/sha1.rs', lines 391:0-401:1 -/
def algorithms.sha1.process_loop_aux
  (block : Array U8 64#usize) (w : alloc.vec.Vec U32) :
  Result (alloc.vec.Vec U32)
  :=
  algorithms.sha1.process_loop_aux_loop block w 0#usize

/- [fips_implementations::algorithms::sha1::process_w_aux]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 406:4-409:5 -/
divergent def algorithms.sha1.process_w_aux_loop
  (w : alloc.vec.Vec U32) (i : Usize) : Result (alloc.vec.Vec U32) :=
  if i < 80#usize
  then
    do
    let i1 ← i - 3#usize
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst U32) w i1
    let i3 ← i - 8#usize
    let i4 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst U32) w i3
    let i5 ← i - 14#usize
    let i6 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst U32) w i5
    let i7 ← i - 16#usize
    let i8 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst U32) w i7
    let i9 := core.num.U32.rotate_left (((i2 ^^^ i4) ^^^ i6) ^^^ i8) 1#u32
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSliceTInst U32)
        w i
    let i10 ← i + 1#usize
    let w1 := index_mut_back i9
    algorithms.sha1.process_w_aux_loop w1 i10
  else Result.ok w

/- [fips_implementations::algorithms::sha1::process_w_aux]:
   Source: 'src/algorithms/sha1.rs', lines 404:0-410:1 -/
def algorithms.sha1.process_w_aux
  (w : alloc.vec.Vec U32) : Result (alloc.vec.Vec U32) :=
  algorithms.sha1.process_w_aux_loop w 16#usize

/- [fips_implementations::algorithms::sha1::process_core_aux]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 421:4-454:5 -/
divergent def algorithms.sha1.process_core_aux_loop
  (w : alloc.vec.Vec U32) (a : U32) (b : U32) (c : U32) (d : U32) (e : U32)
  (i : Usize) :
  Result (Array U32 5#usize)
  :=
  if i < 80#usize
  then
    if 0#usize <= i
    then
      if i <= 19#usize
      then
        do
        let i1 := core.num.U32.rotate_left a 5#u32
        let i2 := core.num.U32.wrapping_add i1 ((b &&& c) ||| ((￢ b) &&& d))
        let i3 := core.num.U32.wrapping_add i2 e
        let i4 := core.num.U32.wrapping_add i3 1518500249#u32
        let i5 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst U32)
            w i
        let temp := core.num.U32.wrapping_add i4 i5
        let c1 := core.num.U32.rotate_left b 30#u32
        let i6 ← i + 1#usize
        algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
      else
        if 20#usize <= i
        then
          if i <= 39#usize
          then
            do
            let i1 := core.num.U32.rotate_left a 5#u32
            let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
            let i3 := core.num.U32.wrapping_add i2 e
            let i4 := core.num.U32.wrapping_add i3 1859775393#u32
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                U32) w i
            let temp := core.num.U32.wrapping_add i4 i5
            let c1 := core.num.U32.rotate_left b 30#u32
            let i6 ← i + 1#usize
            algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
          else
            if 40#usize <= i
            then
              if i <= 59#usize
              then
                do
                let i1 := core.num.U32.rotate_left a 5#u32
                let i2 :=
                  core.num.U32.wrapping_add i1 (((b &&& c) ||| (b &&& d)) |||
                    (c &&& d))
                let i3 := core.num.U32.wrapping_add i2 e
                let i4 := core.num.U32.wrapping_add i3 2400959708#u32
                let i5 ←
                  alloc.vec.Vec.index
                    (core.slice.index.SliceIndexUsizeSliceTInst U32) w i
                let temp := core.num.U32.wrapping_add i4 i5
                let c1 := core.num.U32.rotate_left b 30#u32
                let i6 ← i + 1#usize
                algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
              else
                do
                let i1 := core.num.U32.rotate_left a 5#u32
                let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
                let i3 := core.num.U32.wrapping_add i2 e
                let i4 := core.num.U32.wrapping_add i3 3395469782#u32
                let i5 ←
                  alloc.vec.Vec.index
                    (core.slice.index.SliceIndexUsizeSliceTInst U32) w i
                let temp := core.num.U32.wrapping_add i4 i5
                let c1 := core.num.U32.rotate_left b 30#u32
                let i6 ← i + 1#usize
                algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
            else
              do
              let i1 := core.num.U32.rotate_left a 5#u32
              let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
              let i3 := core.num.U32.wrapping_add i2 e
              let i4 := core.num.U32.wrapping_add i3 3395469782#u32
              let i5 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                  U32) w i
              let temp := core.num.U32.wrapping_add i4 i5
              let c1 := core.num.U32.rotate_left b 30#u32
              let i6 ← i + 1#usize
              algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
        else
          if 40#usize <= i
          then
            if i <= 59#usize
            then
              do
              let i1 := core.num.U32.rotate_left a 5#u32
              let i2 :=
                core.num.U32.wrapping_add i1 (((b &&& c) ||| (b &&& d)) ||| (c
                  &&& d))
              let i3 := core.num.U32.wrapping_add i2 e
              let i4 := core.num.U32.wrapping_add i3 2400959708#u32
              let i5 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                  U32) w i
              let temp := core.num.U32.wrapping_add i4 i5
              let c1 := core.num.U32.rotate_left b 30#u32
              let i6 ← i + 1#usize
              algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
            else
              do
              let i1 := core.num.U32.rotate_left a 5#u32
              let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
              let i3 := core.num.U32.wrapping_add i2 e
              let i4 := core.num.U32.wrapping_add i3 3395469782#u32
              let i5 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                  U32) w i
              let temp := core.num.U32.wrapping_add i4 i5
              let c1 := core.num.U32.rotate_left b 30#u32
              let i6 ← i + 1#usize
              algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
          else
            do
            let i1 := core.num.U32.rotate_left a 5#u32
            let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
            let i3 := core.num.U32.wrapping_add i2 e
            let i4 := core.num.U32.wrapping_add i3 3395469782#u32
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                U32) w i
            let temp := core.num.U32.wrapping_add i4 i5
            let c1 := core.num.U32.rotate_left b 30#u32
            let i6 ← i + 1#usize
            algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
    else
      if 20#usize <= i
      then
        if i <= 39#usize
        then
          do
          let i1 := core.num.U32.rotate_left a 5#u32
          let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
          let i3 := core.num.U32.wrapping_add i2 e
          let i4 := core.num.U32.wrapping_add i3 1859775393#u32
          let i5 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
              U32) w i
          let temp := core.num.U32.wrapping_add i4 i5
          let c1 := core.num.U32.rotate_left b 30#u32
          let i6 ← i + 1#usize
          algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
        else
          if 40#usize <= i
          then
            if i <= 59#usize
            then
              do
              let i1 := core.num.U32.rotate_left a 5#u32
              let i2 :=
                core.num.U32.wrapping_add i1 (((b &&& c) ||| (b &&& d)) ||| (c
                  &&& d))
              let i3 := core.num.U32.wrapping_add i2 e
              let i4 := core.num.U32.wrapping_add i3 2400959708#u32
              let i5 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                  U32) w i
              let temp := core.num.U32.wrapping_add i4 i5
              let c1 := core.num.U32.rotate_left b 30#u32
              let i6 ← i + 1#usize
              algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
            else
              do
              let i1 := core.num.U32.rotate_left a 5#u32
              let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
              let i3 := core.num.U32.wrapping_add i2 e
              let i4 := core.num.U32.wrapping_add i3 3395469782#u32
              let i5 ←
                alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                  U32) w i
              let temp := core.num.U32.wrapping_add i4 i5
              let c1 := core.num.U32.rotate_left b 30#u32
              let i6 ← i + 1#usize
              algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
          else
            do
            let i1 := core.num.U32.rotate_left a 5#u32
            let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
            let i3 := core.num.U32.wrapping_add i2 e
            let i4 := core.num.U32.wrapping_add i3 3395469782#u32
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                U32) w i
            let temp := core.num.U32.wrapping_add i4 i5
            let c1 := core.num.U32.rotate_left b 30#u32
            let i6 ← i + 1#usize
            algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
      else
        if 40#usize <= i
        then
          if i <= 59#usize
          then
            do
            let i1 := core.num.U32.rotate_left a 5#u32
            let i2 :=
              core.num.U32.wrapping_add i1 (((b &&& c) ||| (b &&& d)) ||| (c
                &&& d))
            let i3 := core.num.U32.wrapping_add i2 e
            let i4 := core.num.U32.wrapping_add i3 2400959708#u32
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                U32) w i
            let temp := core.num.U32.wrapping_add i4 i5
            let c1 := core.num.U32.rotate_left b 30#u32
            let i6 ← i + 1#usize
            algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
          else
            do
            let i1 := core.num.U32.rotate_left a 5#u32
            let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
            let i3 := core.num.U32.wrapping_add i2 e
            let i4 := core.num.U32.wrapping_add i3 3395469782#u32
            let i5 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
                U32) w i
            let temp := core.num.U32.wrapping_add i4 i5
            let c1 := core.num.U32.rotate_left b 30#u32
            let i6 ← i + 1#usize
            algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
        else
          do
          let i1 := core.num.U32.rotate_left a 5#u32
          let i2 := core.num.U32.wrapping_add i1 ((b ^^^ c) ^^^ d)
          let i3 := core.num.U32.wrapping_add i2 e
          let i4 := core.num.U32.wrapping_add i3 3395469782#u32
          let i5 ←
            alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst
              U32) w i
          let temp := core.num.U32.wrapping_add i4 i5
          let c1 := core.num.U32.rotate_left b 30#u32
          let i6 ← i + 1#usize
          algorithms.sha1.process_core_aux_loop w temp a c1 c d i6
  else Result.ok (Array.make 5#usize [ a, b, c, d, e ])

/- [fips_implementations::algorithms::sha1::process_core_aux]:
   Source: 'src/algorithms/sha1.rs', lines 413:0-457:1 -/
def algorithms.sha1.process_core_aux
  (state : Array U32 5#usize) (w : alloc.vec.Vec U32) :
  Result ((Array U32 5#usize) × (alloc.vec.Vec U32))
  :=
  do
  let a ← Array.index_usize state 0#usize
  let b ← Array.index_usize state 1#usize
  let c ← Array.index_usize state 2#usize
  let d ← Array.index_usize state 3#usize
  let e ← Array.index_usize state 4#usize
  let a1 ← algorithms.sha1.process_core_aux_loop w a b c d e 0#usize
  Result.ok (a1, w)

/- [alloc::vec::from_elem]:
   Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3172:0-3172:55
   Name pattern: alloc::vec::from_elem -/
axiom alloc.vec.from_elem
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  T → Usize → Result (alloc.vec.Vec T)

/- [fips_implementations::algorithms::sha1::process_aux]:
   Source: 'src/algorithms/sha1.rs', lines 461:0-474:1 -/
def algorithms.sha1.process_aux
  (state : Array U32 5#usize) (block : Array U8 64#usize) :
  Result (Array U32 5#usize)
  :=
  do
  let w ← alloc.vec.from_elem core.clone.CloneU32 0#u32 80#usize
  let w1 ← algorithms.sha1.process_loop_aux block w
  let w2 ← algorithms.sha1.process_w_aux w1
  let (a, _) ← algorithms.sha1.process_core_aux state w2
  let a1 ← Array.index_usize a 0#usize
  let b ← Array.index_usize a 1#usize
  let c ← Array.index_usize a 2#usize
  let d ← Array.index_usize a 3#usize
  let e ← Array.index_usize a 4#usize
  let i ← Array.index_usize state 0#usize
  let i1 := core.num.U32.wrapping_add i a1
  let state1 ← Array.update_usize state 0#usize i1
  let i2 ← Array.index_usize state1 1#usize
  let i3 := core.num.U32.wrapping_add i2 b
  let state2 ← Array.update_usize state1 1#usize i3
  let i4 ← Array.index_usize state2 2#usize
  let i5 := core.num.U32.wrapping_add i4 c
  let state3 ← Array.update_usize state2 2#usize i5
  let i6 ← Array.index_usize state3 3#usize
  let i7 := core.num.U32.wrapping_add i6 d
  let state4 ← Array.update_usize state3 3#usize i7
  let i8 ← Array.index_usize state4 4#usize
  let i9 := core.num.U32.wrapping_add i8 e
  let (_, index_mut_back) ← Array.index_mut_usize state4 4#usize
  Result.ok (index_mut_back i9)

/- [fips_implementations::algorithms::sha1::chunkify]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 480:4-489:5 -/
divergent def algorithms.sha1.chunkify_loop
  (msg : Slice U8) (chunks : alloc.vec.Vec (Array U8 64#usize))
  (msg_start : Usize) :
  Result (alloc.vec.Vec (Array U8 64#usize))
  :=
  let i := Slice.len msg
  if msg_start < i
  then
    do
    let chunk := Array.repeat 64#usize 0#u8
    let msg_end ← msg_start + algorithms.sha1.CHUNK_SIZE
    let msg_slice ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeUsizeSliceTInst U8) msg
        { start := msg_start, end_ := msg_end }
    let (s, index_mut_back) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSliceTIInst
        (core.slice.index.SliceIndexRangeUsizeSliceTInst U8)) chunk
        { start := 0#usize, end_ := algorithms.sha1.CHUNK_SIZE }
    let s1 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s msg_slice
    let chunk1 := index_mut_back s1
    let chunks1 ← alloc.vec.Vec.push chunks chunk1
    let msg_start1 ← msg_start + algorithms.sha1.CHUNK_SIZE
    algorithms.sha1.chunkify_loop msg chunks1 msg_start1
  else Result.ok chunks

/- [fips_implementations::algorithms::sha1::chunkify]:
   Source: 'src/algorithms/sha1.rs', lines 476:0-491:1 -/
def algorithms.sha1.chunkify
  (msg : Slice U8) : Result (alloc.vec.Vec (Array U8 64#usize)) :=
  algorithms.sha1.chunkify_loop msg (alloc.vec.Vec.new (Array U8 64#usize))
    0#usize

/- [fips_implementations::algorithms::sha1::pad_message_loop]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 496:4-499:5 -/
divergent def algorithms.sha1.pad_message_loop_loop
  (padded_msg : alloc.vec.Vec U8) (zero_padding_length : Usize) (i : Usize) :
  Result (alloc.vec.Vec U8)
  :=
  if i < zero_padding_length
  then
    do
    let padded_msg1 ← alloc.vec.Vec.push padded_msg 0#u8
    let i1 ← i + 1#usize
    algorithms.sha1.pad_message_loop_loop padded_msg1 zero_padding_length i1
  else Result.ok padded_msg

/- [fips_implementations::algorithms::sha1::pad_message_loop]:
   Source: 'src/algorithms/sha1.rs', lines 494:0-500:1 -/
def algorithms.sha1.pad_message_loop
  (padded_msg : alloc.vec.Vec U8) (zero_padding_length : Usize) :
  Result (alloc.vec.Vec U8)
  :=
  algorithms.sha1.pad_message_loop_loop padded_msg zero_padding_length 0#usize

/- [fips_implementations::algorithms::sha1::pad_message]:
   Source: 'src/algorithms/sha1.rs', lines 502:0-532:1 -/
def algorithms.sha1.pad_message (msg : Slice U8) : Result (alloc.vec.Vec U8) :=
  do
  let i := Slice.len msg
  let i1 ← Scalar.cast .U64 i
  let msg_len_bits ← i1 * 8#u64
  let i2 := Slice.len msg
  let i3 ← i2 + 1#usize
  let i4 ← i3 + 64#usize
  let padded_msg := alloc.vec.Vec.with_capacity U8 i4
  let padded_msg1 ←
    alloc.vec.Vec.extend_from_slice core.clone.CloneU8 padded_msg msg
  let padded_msg2 ← alloc.vec.Vec.push padded_msg1 128#u8
  let i5 := alloc.vec.Vec.len padded_msg2
  let i6 ← i5 % 64#usize
  let i7 ← 56#usize - i6
  let zero_padding_length ← i7 % 64#usize
  let padded_msg3 ←
    algorithms.sha1.pad_message_loop padded_msg2 zero_padding_length
  let i8 ← msg_len_bits >>> 56#u64
  let i9 ← Scalar.cast .U8 (i8 &&& 255#u64)
  let i10 ← msg_len_bits >>> 48#u64
  let i11 ← Scalar.cast .U8 (i10 &&& 255#u64)
  let i12 ← msg_len_bits >>> 40#u64
  let i13 ← Scalar.cast .U8 (i12 &&& 255#u64)
  let i14 ← msg_len_bits >>> 32#u64
  let i15 ← Scalar.cast .U8 (i14 &&& 255#u64)
  let i16 ← msg_len_bits >>> 24#u64
  let i17 ← Scalar.cast .U8 (i16 &&& 255#u64)
  let i18 ← msg_len_bits >>> 16#u64
  let i19 ← Scalar.cast .U8 (i18 &&& 255#u64)
  let i20 ← msg_len_bits >>> 8#u64
  let i21 ← Scalar.cast .U8 (i20 &&& 255#u64)
  let i22 ← msg_len_bits >>> 0#u64
  let i23 ← Scalar.cast .U8 (i22 &&& 255#u64)
  let s ←
    Array.to_slice
      (Array.make 8#usize [ i9, i11, i13, i15, i17, i19, i21, i23 ])
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 padded_msg3 s

/- [fips_implementations::algorithms::sha1::hash_to_vec]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 537:4-545:5 -/
divergent def algorithms.sha1.hash_to_vec_loop
  (final_hash : Array U32 5#usize) (result_bytes : alloc.vec.Vec U8)
  (index : Usize) :
  Result (alloc.vec.Vec U8)
  :=
  do
  let s ← Array.to_slice final_hash
  let i := Slice.len s
  if index < i
  then
    do
    let word ← Array.index_usize final_hash index
    let i1 ← word >>> 24#u32
    let i2 ← Scalar.cast .U8 (i1 &&& 255#u32)
    let result_bytes1 ← alloc.vec.Vec.push result_bytes i2
    let i3 ← word >>> 16#u32
    let i4 ← Scalar.cast .U8 (i3 &&& 255#u32)
    let result_bytes2 ← alloc.vec.Vec.push result_bytes1 i4
    let i5 ← word >>> 8#u32
    let i6 ← Scalar.cast .U8 (i5 &&& 255#u32)
    let result_bytes3 ← alloc.vec.Vec.push result_bytes2 i6
    let i7 ← word >>> 0#u32
    let i8 ← Scalar.cast .U8 (i7 &&& 255#u32)
    let result_bytes4 ← alloc.vec.Vec.push result_bytes3 i8
    let index1 ← index + 1#usize
    algorithms.sha1.hash_to_vec_loop final_hash result_bytes4 index1
  else Result.ok result_bytes

/- [fips_implementations::algorithms::sha1::hash_to_vec]:
   Source: 'src/algorithms/sha1.rs', lines 534:0-547:1 -/
def algorithms.sha1.hash_to_vec
  (final_hash : Array U32 5#usize) : Result (alloc.vec.Vec U8) :=
  algorithms.sha1.hash_to_vec_loop final_hash (alloc.vec.Vec.new U8) 0#usize

/- [fips_implementations::algorithms::sha1::hash]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 554:4-558:5 -/
divergent def algorithms.sha1.hash_loop
  (chunks : alloc.vec.Vec (Array U8 64#usize)) (state : Array U32 5#usize)
  (chunk_index : Usize) :
  Result (alloc.vec.Vec U8)
  :=
  let i := alloc.vec.Vec.len chunks
  if chunk_index < i
  then
    do
    let chunk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst (Array U8
        64#usize)) chunks chunk_index
    let state1 ← algorithms.sha1.process state chunk
    let chunk_index1 ← chunk_index + 1#usize
    algorithms.sha1.hash_loop chunks state1 chunk_index1
  else algorithms.sha1.hash_to_vec state

/- [fips_implementations::algorithms::sha1::hash]:
   Source: 'src/algorithms/sha1.rs', lines 549:0-560:1 -/
def algorithms.sha1.hash (message : Slice U8) : Result (alloc.vec.Vec U8) :=
  do
  let padded_msg ← algorithms.sha1.pad_message message
  let s := alloc.vec.DerefVec.deref padded_msg
  let chunks ← algorithms.sha1.chunkify s
  algorithms.sha1.hash_loop chunks algorithms.sha1.INITIAL_STATE 0#usize

/- [fips_implementations::algorithms::sha1::hash_aux]: loop 0:
   Source: 'src/algorithms/sha1.rs', lines 568:4-572:5 -/
divergent def algorithms.sha1.hash_aux_loop
  (chunks : alloc.vec.Vec (Array U8 64#usize)) (state : Array U32 5#usize)
  (chunk_index : Usize) :
  Result (alloc.vec.Vec U8)
  :=
  let i := alloc.vec.Vec.len chunks
  if chunk_index < i
  then
    do
    let chunk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceTInst (Array U8
        64#usize)) chunks chunk_index
    let state1 ← algorithms.sha1.process_aux state chunk
    let chunk_index1 ← chunk_index + 1#usize
    algorithms.sha1.hash_aux_loop chunks state1 chunk_index1
  else algorithms.sha1.hash_to_vec state

/- [fips_implementations::algorithms::sha1::hash_aux]:
   Source: 'src/algorithms/sha1.rs', lines 563:0-574:1 -/
def algorithms.sha1.hash_aux
  (message : Slice U8) : Result (alloc.vec.Vec U8) :=
  do
  let padded_msg ← algorithms.sha1.pad_message message
  let s := alloc.vec.DerefVec.deref padded_msg
  let chunks ← algorithms.sha1.chunkify s
  algorithms.sha1.hash_aux_loop chunks algorithms.sha1.INITIAL_STATE 0#usize

end fips_implementations
